package app;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.testng.annotations.*;

import static org.testng.Assert.*;

public class BinaryConverterTest {

    @DataProvider(name = "correctDataProvider")
    private Object[][] correctDataProvider() {
        return new Object[][]{{3, "11"},{ 5, "101"}};
    }

    @Test(dataProvider = "correctDataProvider")
    public void correctConversionTest(int number, String expected) {
        // given
        BinaryConverter binaryConverter = new BinaryConverter();

        // when
        String result = binaryConverter.binaryConverter(number);

        // then
        assertEquals(result, expected);
    }

}
/**  @Test public void nonExistentPathGetsAZero() {
        App classUnderTest = new App();
// seting my own input stream so in unit test scanner gets it
        final String pathFromUser = "aaaaa";
        System.setIn(new ByteArrayInputStream(pathFromUser.getBytes()));
        assertEquals(classUnderTest.count(Paths.get(pathFromUser)), 0,
                "path " + pathFromUser + " doesn't exist, so should be zero");
        // resetting the scanner back
        System.setIn(System.in);
    }*/
