package app;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.testng.annotations.*;

import static org.testng.Assert.*;

    public class BinaryConverterTest {

        @DataProvider(name = "correctDataProvider")
        private Object[][] correctDataProvider() {
            return new Object[][]{{3, "11"},{ 5, "101"}};
        }

        @Test(dataProvider = "correctDataProvider")
        public void correctConversionTest(int number, String expected) {
            // given
            BinaryConverter binaryConverter = new BinaryConverter();

            // when
            String result = binaryConverter.binaryConverter(number);

            // then
            assertEquals(result, expected);
        }

}
